baseURL = 'http://example.org/'
languageCode = 'zh-cn'
title = '我的技术博客'
theme = 'PaperMod'

[params]
    mermaid = true
    math = true

    [params.homeInfoParams]
        Title = '我的技术博客'
        Content = '欢迎交流。'

    [[params.socialIcons]]
        name = 'github'
        title = 'GitHub'
        url = 'https://github.com/buvidk1234'

[outputs]
    home = ['HTML', 'RSS', 'JSON']

[menu]
    [[menu.main]]
        identifier = 'archives'
        name = 'Archive'
        url = '/archives/'
        weight = 10

    [[menu.main]]
        identifier = 'search'
        name = 'Search'
        url = '/search/'
        weight = 20

    [[menu.main]]
        identifier = 'tags'
        name = 'Tags'
        url = '/tags/'
        weight = 30

[markup]
    [markup.highlight]
        noClasses = false
        style = 'github'
    [markup.goldmark]
        [markup.goldmark.extensions]
            [markup.goldmark.extensions.passthrough]
                enable = true
                [markup.goldmark.extensions.passthrough.delimiters]
                    block = [['$$', '$$'], ['\[', '\]']]
                    inline = [['$', '$'], ['\(', '\)']]
